version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_standalone
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    command: ["--auth"]

volumes:
  mongodb_data: